apiVersion: v1
kind: Service
metadata:
  name: preferences
  labels:
    app: preferences
spec:
  type: NodePort
  ports:
    - port: 9009
      name: preferences
      nodePort: 30400
      protocol: TCP
      targetPort: 9009
  selector:
    app: preferences
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preferences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preferences
  template:
    metadata:
      labels:
        app: preferences
    spec:
      imagePullSecrets:
      - name: workshop-registry
      containers:
      - name: preferences
        image: workshop-registry:5000/preferences:2.2.1
        ports:
        - containerPort: 9009
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://172.21.186.51:3306/preferences?useSSL=false&allowPublicKeyRetrieval=true
        - name: URL_PROXY
          value: http://proxy
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9009
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
          failureThreshold: 1

